#!/usr/bin/env bash
# Script displays list of currently running processes
# Must show all processes, for all users, including those which might not have a TTY
# This Display a user-oriented format
# Show process hierarchy

ps -a -x -u -f
